.libPaths(c("/home/shenlm/R/x86_64-pc-linux-gnu-library/4.1","/opt/R/4.1.2/lib/R/library"))
library(getopt)
library(ggplot2)
library(reshape2)
library(tidyverse)

spec = matrix(c('input','i',1,"character",'work_dir','w',1,"character",'function_file','f',1,"character"),byrow = TRUE,ncol = 4)
opt = getopt(spec)
setwd(opt$work_dir)
source(opt$function_file)

fpkm_melt <- read.table(opt$input,header = FALSE,sep=" ")
fpkm_melt <- data.frame(gene=fpkm_melt$V1,sample=fpkm_melt$V3,fpkm=fpkm_melt$V2)
fpkm_melt <- unique(fpkm_melt)
fpkm_melt$fpkm <- as.numeric(as.character(fpkm_melt$fpkm))
#head(fpkm_melt)
fpkm_melt <- na.omit(fpkm_melt)
fpkm_raw <- dcast(fpkm_melt,gene~sample,fun.aggregate=mean)
#head(fpkm_raw)

fpkm_melt$sample <- as.factor(fpkm_melt$sample)
fpkm_melt$fpkm <- log10(fpkm_melt$fpkm+1)
fpkm_melt<-subset(fpkm_melt, fpkm_melt$fpkm > 0)
fpkm_raw_tmp <- dcast(fpkm_melt,gene~sample,fun.aggregate=mean)
#colnames(fpkm_raw_tmp) <- paste(colnames(fpkm_raw_tmp),0:(length(fpkm_raw_tmp)-1),sep = ',')
colnames(fpkm_raw_tmp)[1] <- c("gene")
fpkm_melt_tmp <- melt(data = fpkm_raw_tmp,id.vars=c("gene"),na.rm = TRUE)
#fpkm_melt_tmp<-separate(fpkm_melt_tmp,variable,into = c("index","sample"),sep = ":",remove = FALSE)
#fpkm_melt_tmp$index <- factor(fpkm_melt_tmp$index,levels = c(1:length(colnames(fpkm_raw_tmp))-1),ordered = TRUE)
#write.table(fpkm_melt,"gene_fpkm_matrix_melt.csv",sep=',',row.names=FALSE)
write.table(fpkm_raw,"gene_fpkm_matrix.csv",sep=',',row.names=FALSE)

fpkm <- fpkm_dis_boxplot_rename(fpkm_melt_tmp)
ggsave("gene_fpkm_dis_html.png",fpkm,width=5,height=5,dpi = 600)
ggsave("gene_fpkm_dis.pdf",fpkm,width=5,height=5)
gene_fpkm_matrix <- fpkm_raw[which(rowSums(fpkm_raw[,-1]) > 0),]
gene_fpkm_matrix <- (gene_fpkm_matrix[,-1]+1)^0.5
#png("Scatterplot.png",width=250,height=250)
#scatter_plot(gene_fpkm_matrix)
#dev.off()
